language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: jruby
    - rvm: rbx
env:
  - DB=postgresql
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ocs_test' -U postgres
  - export JRUBY_OPTS="--1.9 -Xcext.enabled=true"
bundler_args: --without development
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec --color