language: ruby
rvm:
  - 2.0.0
  - rbx
  - jruby
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
env:
  - DB=postgresql
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ocs_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec --color