language: ruby
rvm:
  - jruby
  - 2.1.0
  - 2.0.0
  - rbx
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: rbx
    - rvm: jruby
env:
  - DB=postgresql
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database ocs_test' -U postgres
bundler_args: --without development
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec --color