require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollectorsController do

  before (:each) do
    @user = FactoryGirl.create(:user)
    sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # Collector. As you add validations to Collector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString", "file" => fixture_file_upload('/files/fake.txt') } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollectorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all collectors as @collectors" do
      collector = Collector.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collectors).should eq([collector])
    end
  end

  describe "GET show" do
    it "assigns the requested collector as @collector" do
      collector = Collector.create! valid_attributes
      get :show, {:id => collector.to_param}, valid_session
      assigns(:collector).should eq(collector)
    end
  end

  describe "GET new" do
    it "assigns a new collector as @collector" do
      get :new, {}, valid_session
      assigns(:collector).should be_a_new(Collector)
    end
  end

  describe "GET edit" do
    it "assigns the requested collector as @collector" do
      collector = Collector.create! valid_attributes
      get :edit, {:id => collector.to_param}, valid_session
      assigns(:collector).should eq(collector)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Collector" do
        expect {
          post :create, {:collector => valid_attributes}, valid_session
        }.to change(Collector, :count).by(1)
      end

      it "assigns a newly created collector as @collector" do
        post :create, {:collector => valid_attributes}, valid_session
        assigns(:collector).should be_a(Collector)
        assigns(:collector).should be_persisted
      end

      it "redirects to the created collector" do
        post :create, {:collector => valid_attributes}, valid_session
        response.should redirect_to(Collector.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collector as @collector" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collector.any_instance.stub(:save).and_return(false)
        post :create, {:collector => { "name" => "invalid value" }}, valid_session
        assigns(:collector).should be_a_new(Collector)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collector.any_instance.stub(:save).and_return(false)
        post :create, {:collector => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collector" do
        collector = Collector.create! valid_attributes
        # Assuming there are no other collectors in the database, this
        # specifies that the Collector created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Collector.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => collector.to_param, :collector => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested collector as @collector" do
        collector = Collector.create! valid_attributes
        put :update, {:id => collector.to_param, :collector => valid_attributes}, valid_session
        assigns(:collector).should eq(collector)
      end

      it "redirects to the collector" do
        collector = Collector.create! valid_attributes
        put :update, {:id => collector.to_param, :collector => valid_attributes}, valid_session
        response.should redirect_to(collector)
      end
    end

    describe "with invalid params" do
      it "assigns the collector as @collector" do
        collector = Collector.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collector.any_instance.stub(:save).and_return(false)
        put :update, {:id => collector.to_param, :collector => { "name" => "invalid value" }}, valid_session
        assigns(:collector).should eq(collector)
      end

      it "re-renders the 'edit' template" do
        collector = Collector.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Collector.any_instance.stub(:save).and_return(false)
        put :update, {:id => collector.to_param, :collector => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collector" do
      collector = Collector.create! valid_attributes
      expect {
        delete :destroy, {:id => collector.to_param}, valid_session
      }.to change(Collector, :count).by(-1)
    end

    it "redirects to the collectors list" do
      collector = Collector.create! valid_attributes
      delete :destroy, {:id => collector.to_param}, valid_session
      response.should redirect_to(collectors_url)
    end
  end

end
