require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TotosController do

  # This should return the minimal set of attributes required to create a valid
  # Toto. As you add validations to Toto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "test" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TotosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all totos as @totos" do
      toto = Toto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:totos).should eq([toto])
    end
  end

  describe "GET show" do
    it "assigns the requested toto as @toto" do
      toto = Toto.create! valid_attributes
      get :show, {:id => toto.to_param}, valid_session
      assigns(:toto).should eq(toto)
    end
  end

  describe "GET new" do
    it "assigns a new toto as @toto" do
      get :new, {}, valid_session
      assigns(:toto).should be_a_new(Toto)
    end
  end

  describe "GET edit" do
    it "assigns the requested toto as @toto" do
      toto = Toto.create! valid_attributes
      get :edit, {:id => toto.to_param}, valid_session
      assigns(:toto).should eq(toto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Toto" do
        expect {
          post :create, {:toto => valid_attributes}, valid_session
        }.to change(Toto, :count).by(1)
      end

      it "assigns a newly created toto as @toto" do
        post :create, {:toto => valid_attributes}, valid_session
        assigns(:toto).should be_a(Toto)
        assigns(:toto).should be_persisted
      end

      it "redirects to the created toto" do
        post :create, {:toto => valid_attributes}, valid_session
        response.should redirect_to(Toto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved toto as @toto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Toto.any_instance.stub(:save).and_return(false)
        post :create, {:toto => { "test" => "invalid value" }}, valid_session
        assigns(:toto).should be_a_new(Toto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Toto.any_instance.stub(:save).and_return(false)
        post :create, {:toto => { "test" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested toto" do
        toto = Toto.create! valid_attributes
        # Assuming there are no other totos in the database, this
        # specifies that the Toto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Toto.any_instance.should_receive(:update).with({ "test" => "MyString" })
        put :update, {:id => toto.to_param, :toto => { "test" => "MyString" }}, valid_session
      end

      it "assigns the requested toto as @toto" do
        toto = Toto.create! valid_attributes
        put :update, {:id => toto.to_param, :toto => valid_attributes}, valid_session
        assigns(:toto).should eq(toto)
      end

      it "redirects to the toto" do
        toto = Toto.create! valid_attributes
        put :update, {:id => toto.to_param, :toto => valid_attributes}, valid_session
        response.should redirect_to(toto)
      end
    end

    describe "with invalid params" do
      it "assigns the toto as @toto" do
        toto = Toto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Toto.any_instance.stub(:save).and_return(false)
        put :update, {:id => toto.to_param, :toto => { "test" => "invalid value" }}, valid_session
        assigns(:toto).should eq(toto)
      end

      it "re-renders the 'edit' template" do
        toto = Toto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Toto.any_instance.stub(:save).and_return(false)
        put :update, {:id => toto.to_param, :toto => { "test" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested toto" do
      toto = Toto.create! valid_attributes
      expect {
        delete :destroy, {:id => toto.to_param}, valid_session
      }.to change(Toto, :count).by(-1)
    end

    it "redirects to the totos list" do
      toto = Toto.create! valid_attributes
      delete :destroy, {:id => toto.to_param}, valid_session
      response.should redirect_to(totos_url)
    end
  end

end
